import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins, Syne } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  style: ['normal', 'italic'],
  variable: '--font-poppins'
});

const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-syne'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${syne.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
